# Generated by Django 3.2.3 on 2021-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahumano',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metahumano',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
