---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: git clone
      git:
        repo: https://github.com/orsibiro/shield.git
        dest: "{{ install_root }}/shield"
        accept_hostkey: yes
        force: true

    - name: Install python packages
      pip:
        requirements: "{{ install_root }}/{{ project_name }}/requirements.txt"

    - name: giving permissions to file manage.py
      file:
        path: "{{ install_root }}/{{ project_name }}/manage.py"
        mode: '0777'

    - name: django migrate
      django_manage:
        command: migrate
        project_path: "{{ install_root }}/{{ project_name }}"

    - name: django load data
      django_manage:
        command: loaddata
        project_path: "{{ install_root }}/{{ project_name }}"
        fixtures: "{{ install_root }}/{{ project_name }}/metahumans/fixtures/initial_data.json" 

        

    