---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt:
        name: "{{ system_packages }}"
        update_cache: true

    - name: Create root/.ssh directory
      file:
        path: /root/.ssh
        state: directory
      
    - name: Save ssh key to server
      copy:
        src: "{{ ssh_private_key }}"
        dest: "/root/.ssh/id_rsa"
        mode: 0600

    - name: Create directory for app
      file:
        path: "{{ install_root }}/{{ project_name }}"
        state: directory

- import_playbook: deploy.yml